# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='checkOnFrequency',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='container',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='moreInfoLink',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(max_length=25),
        ),
    ]
