# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_auto_20170123_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='bestByDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='calPerServing',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='checkOnFrequency',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='moreInfoLink',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='numServings',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchaseDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='waterStored',
            field=models.IntegerField(blank=True),
        ),
    ]
