# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_auto_20170123_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='container',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='numServings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
