# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0005_auto_20170123_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='waterStored',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
